# Generated by Django 5.1.6 on 2025-02-21 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название курса', max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Введите описание курса', null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, help_text='Вставьте изображение курса', null=True, upload_to='products/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название урока', max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, help_text='Введите описание урока', null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение урока', null=True, upload_to='products/', verbose_name='Изображение')),
                ('course', models.ForeignKey(blank=True, help_text='В каком курсе урок?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='zifirkaguide.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['name'],
                'permissions': [],
            },
        ),
    ]
